#	Website settings - change the CookieKey to some other secret value
[Website]
	HTTPPort    = "8000"
	CookieKey   = "CookieEncryptionKey"
	# Recommended to set true if HTTPS is available for the site (true or false)
	SecureHTTPS = false
